### ISSUE TITLE
Analisis Daerah Jawa Barat

### ISSUE THREAD

**Issue by Shalrizky** [Shalrizky/Analisis-Pariwisata-Gamification#7]
Menganalisis Terkait Deskripsi Foto Dll Tentang Daerah Apa Saja Yang Ada Di Jawa Barat

**Comment by Shalrizky** [comment]
Revisi ya harus ditambahkan dan dikelompokan yaaa seperti pembahasan pada rapat

**Comment by reykialmadani** [comment]
untuk penjelasan kotanya kayanya terlalu template, lebih ke analisis kotanya ajaa, jgn data yang di tumplekin

**Comment by reykialmadani** [comment]
done
