### ISSUE TITLE
Analisis Kuliner Khas Daerah Jawa Barat

### ISSUE THREAD

**Issue by Shalrizky** [Shalrizky/Analisis-Pariwisata-Gamification#8]
Menganalisis Terkait Deskripsi Foto Dll Tentang Apa Saja Kuliner Yang Ada Di Jawa Barat

**Comment by Mortalsinner** [comment]
Udah gua tambahin 10 lagi tuh ya ganteng

**Comment by Shalrizky** [comment]
revisi ya sesuai pembahasa rapat yaaa ditambahkan deskripsi sejarah dan mungkin ada tempat makan rekomendasi dll
